Insert Into AVATAR(NAME.THUMBNAIL) VALUES ("가영","가영썸네일");
Insert Into AVATAR(NAME.THUMBNAIL) VALUES ("나영","나영썸네일");
Insert Into AVATAR(NAME.THUMBNAIL) VALUES ("다영","다영썸네일");

Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("썬글라스","1");
Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("마스크","1");
Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("빨간넥타이","1");

Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("귀걸이","2");
Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("입술피어싱","2");
Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("노랑모자","2");

Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("노랑모자","3");
Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("빨간모자","3");
Insert Into ACESSORIES(ACCESSORYURL,AVATARID) VALUES ("파랑모자","3");


Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("공손하게","1");
Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("역동적이게","1");
Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("큰 제스처와 함께","1");

Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("공손하게","2");
Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("역동적이게","2");
Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("큰 제스처와 함께","2");

Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("공손하게","3");
Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("역동적이게","3");
Insert Into ATTITUDE(ATTITUDEURL,AVATARID) VALUES ("큰 제스처와 함께","3");


Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("빨강 자켓","1");
Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("파랑 자켓","1");
Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("검정 자켓","1");

Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("빨강 교복","2");
Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("파랑 교복","2");
Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("검정 교복","2");

Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("빨강 셔츠","3");
Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("파랑 셔츠","3");
Insert Into CLOTHES(CLOTHESURL,AVATARID) VALUES ("검정 셔츠","3");
